version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
